Repository BrainlessLabs/momo, pull requests merged in 2019-10, with the labels that each got.

#16 Creating the initial structure
  .gitignore
  NOTICE
  build.gradle
  src/main/java/com/brainlesslabs/momo/Main.java
  src/main/java/com/brainlesslabs/momo/common/DbStatus.java
  src/main/java/com/brainlesslabs/momo/common/MomoBase.java
  src/main/java/com/brainlesslabs/momo/common/MomoIterator.java
  src/main/java/com/brainlesslabs/momo/common/Options.java
  src/main/java/com/brainlesslabs/momo/common/ReadOptions.java
  src/main/java/com/brainlesslabs/momo/common/Snapshot.java
  src/main/java/com/brainlesslabs/momo/common/WriteOptions.java
  src/main/java/com/brainlesslabs/momo/common/consts/CompressionMode.java
  src/main/java/com/brainlesslabs/momo/common/consts/CreateOptions.java
  src/main/java/com/brainlesslabs/momo/common/consts/EncryptionMode.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/DataCorruptedException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/FailedException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/IOErrorException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/InvalidArgumentsException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/InvalidOperationException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/MomoErrorCodes.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/MomoException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/NotFoundException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/NotImplementedException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/NotSupportedException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/OperationIncompleteException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/OutOfStorageException.java
  src/main/java/com/brainlesslabs/momo/common/utils/Murmur3.java
  src/main/java/com/brainlesslabs/momo/examples/KeyStore.java
  src/main/java/com/brainlesslabs/momo/examples/MemoryStore.java
Labels: Hacktoberfest, design, enhancement

#18 Updated README file and added jar task in build.gradle
  README.md
  build.gradle
Labels: Hacktoberfest, documentation, good first issue, help wanted

#19 Bringing more structure to the changes
  build.gradle
  src/main/java/com/brainlesslabs/momo/common/MomoBase.java
  src/main/java/com/brainlesslabs/momo/common/options/Options.java
  src/main/java/com/brainlesslabs/momo/common/options/ReadOptions.java
  src/main/java/com/brainlesslabs/momo/common/options/WriteOptions.java
  src/main/java/com/brainlesslabs/momo/common/policies/CompressionPolicy.java
  src/main/java/com/brainlesslabs/momo/common/policies/HashPolicy.java
  src/main/java/com/brainlesslabs/momo/common/policies/StoragePolicy.java
  src/main/java/com/brainlesslabs/momo/examples/Main.java
  src/main/java/com/brainlesslabs/momo/impl/linklistheadcell/options/LinkListOptions.java
Labels: Hacktoberfest, design, enhancement, good first issue

#20 Some more changes
  README.md
  _config.yml
  build.gradle
  src/main/java/com/brainlesslabs/momo/common/DbStatus.java
  src/main/java/com/brainlesslabs/momo/common/MomoBase.java
  src/main/java/com/brainlesslabs/momo/common/Options.java
  src/main/java/com/brainlesslabs/momo/common/ReadOptions.java
  src/main/java/com/brainlesslabs/momo/common/Snapshot.java
  src/main/java/com/brainlesslabs/momo/common/WriteOptions.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/CompressionException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/FileOperationException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/HashException.java
  src/main/java/com/brainlesslabs/momo/common/exceptions/MomoErrorCodes.java
  src/main/java/com/brainlesslabs/momo/common/options/Options.java
  src/main/java/com/brainlesslabs/momo/common/policies/BackupPolicy.java
  src/main/java/com/brainlesslabs/momo/common/policies/CompressionPolicy.java
  src/main/java/com/brainlesslabs/momo/common/policies/HashPolicy.java
  src/main/java/com/brainlesslabs/momo/common/policies/LZ4Compression.java
  src/main/java/com/brainlesslabs/momo/common/policies/ReplicationPolicy.java
  src/main/java/com/brainlesslabs/momo/common/policies/SnappyCompression.java
  src/main/java/com/brainlesslabs/momo/common/policies/StoragePolicy.java
  src/main/java/com/brainlesslabs/momo/common/policies/XXHashing.java
  src/main/java/com/brainlesslabs/momo/common/utils/ByteSlice.java
  src/main/java/com/brainlesslabs/momo/common/utils/ConversionUtils.java
  src/main/java/com/brainlesslabs/momo/common/utils/DbStatus.java
  src/main/java/com/brainlesslabs/momo/common/utils/MomoIterator.java
  src/main/java/com/brainlesslabs/momo/common/utils/Murmur3.java
  src/main/java/com/brainlesslabs/momo/common/utils/Pair.java
  src/main/java/com/brainlesslabs/momo/common/utils/SimpleLRUCache.java
  src/main/java/com/brainlesslabs/momo/common/utils/Snapshot.java
  src/main/java/com/brainlesslabs/momo/common/utils/StopWatch.java
  src/main/java/com/brainlesslabs/momo/examples/Main.java
  src/main/java/com/brainlesslabs/momo/impl/linklistheadcell/options/LinkListOptions.java
  src/main/java/com/brainlesslabs/momo/impl/simplefilelinklist/HeadMetadata.java
  src/main/java/com/brainlesslabs/momo/impl/simplefilelinklist/LinkListOptions.java
  src/main/java/com/brainlesslabs/momo/impl/simplefilelinklist/MomoSimpleFileLinkedList.java
  src/main/java/com/brainlesslabs/momo/impl/simplefilelinklist/SimpleFileListStorage.java
  src/main/java/com/brainlesslabs/momo/impl/simplefilelinklist/SimpleLinkedFileRecord.java
Labels: Hacktoberfest, design, enhancement
